@host = http://localhost:5000
@securehost = https://localhost:5001
@content = application/json
@accept = application/json

###

# @name login
POST {{host}}/api/auth/login HTTP/1.1
Content-Type: {{content}}

{
    "username": "username",
    "password": "password"
}
###

// GET ALL VALUES
# @name getValues
GET {{host}}/api/values HTTP/1.1
Accept: {{accept}}
Authorization: Bearer {{login.response.body.tokenString}}
###

// GET ITEM
# @name getValue
GET {{host}}/api/values/1 HTTP/1.1
Accept: {{accept}}
Authorization: Bearer {{login.response.body.tokenString}}

###

// REGISTER EXISTING USER
# @name register
POST {{host}}/api/auth/register HTTP/1.1
Content-Type: {{content}}

{
    "username": "username",
    "password": "password"
}
###
// REGISTER NEW USER
POST {{host}}/api/auth/register HTTP/1.1
Content-Type: {{content}}

{
    "username": "{{$guid}}",
    "password": "{{$randomInt 1000 99999999}}"
}
###

// REGISTER WITH AN Username TAKEN
POST {{host}}/api/auth/register HTTP/1.1
Content-Type: {{content}}

{
    "username": "user",
    "password": "{{$randomInt 1000 99999999}}"
}
###

// REGISTER INVALID USER INFO
POST {{host}}/api/auth/register HTTP/1.1
Content-Type: {{content}}

{
    "username": "",
    "password": ""
}
###
// REGISTER WITH Username NULL
POST {{host}}/api/auth/register HTTP/1.1
Content-Type: {{content}}

{
    "username": "",
    "password": "{{$randomInt 1000 99999999}}"
}
###
// Register username and password
POST {{host}}/api/auth/login HTTP/1.1
Content-Type: {{content}}

{
    "username": "username",
    "password": "password"
}
###
